name: Update Docs

on:
  push:
    branches:
      - main

jobs:
  update-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install MkDocs
        run: |
          python -m pip install mkdocs
          python -m pip install "mkdocstrings[python]"
          python -m pip install mkdocs-material

      - name: Build Documentation
        run: mkdocs build

      - name: Deploy Documentation
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          publish_dir: ./site
          user_name: GitHub Actions
          user_email: actions@github.com
          publish_branch: gh-pages
